In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = [1.5, 7.5, 3.4, 4.1, 5.0, 1.0]
ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)

<TensorSliceDataset shapes: (), types: tf.float32>


In [3]:
for item in ds:
    print(item)

tf.Tensor(1.5, shape=(), dtype=float32)
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(4.1, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [5]:
tf.random.set_seed(1)
t_x = tf.random.uniform([4, 3], dtype = tf.float32)
t_y = tf.range(4)
print(t_x)
print(t_y)

tf.Tensor(
[[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]
 [0.60489583 0.6366315  0.6144488 ]], shape=(4, 3), dtype=float32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)


In [8]:
ds_x = tf.data.Dataset.from_tensor_slices(t_x)
ds_y = tf.data.Dataset.from_tensor_slices(t_y)
ds_joint = tf.data.Dataset.zip((ds_x, ds_y))
for example in ds_joint:
    print('x:', example[0].numpy(),
         'y:', example[1].numpy())

x: [0.16513085 0.9014813  0.6309742 ] y: 0
x: [0.4345461  0.29193902 0.64250207] y: 1
x: [0.9757855  0.43509948 0.6601019 ] y: 2
x: [0.60489583 0.6366315  0.6144488 ] y: 3


In [9]:
ds_joint = tf.data.Dataset.from_tensor_slices((t_x, t_y))
for example in ds_joint:
    print('x:', example[0].numpy(),
         'y:', example[1].numpy())

x: [0.16513085 0.9014813  0.6309742 ] y: 0
x: [0.4345461  0.29193902 0.64250207] y: 1
x: [0.9757855  0.43509948 0.6601019 ] y: 2
x: [0.60489583 0.6366315  0.6144488 ] y: 3


In [10]:
ds_trans = ds_joint.map(lambda x, y: (x*2 - 1.0, y))
for example in ds_trans:
    print('x:', example[0].numpy(),
         'y:', example[1].numpy())

x: [-0.6697383   0.80296254  0.26194835] y: 0
x: [-0.13090777 -0.41612196  0.28500414] y: 1
x: [ 0.951571   -0.12980103  0.32020378] y: 2
x: [0.20979166 0.27326298 0.22889757] y: 3


In [11]:
#Shuffle
tf.random.set_seed(2)
shuffle = ds_joint.shuffle(buffer_size = len(t_x))
for example in shuffle:
    print('x:', example[0].numpy(),
         'y:', example[1].numpy())

x: [0.60489583 0.6366315  0.6144488 ] y: 3
x: [0.16513085 0.9014813  0.6309742 ] y: 0
x: [0.4345461  0.29193902 0.64250207] y: 1
x: [0.9757855  0.43509948 0.6601019 ] y: 2


In [12]:
#Batch
ds = ds_joint.batch(batch_size = 3, drop_remainder = False)
batch_x, batch_y = next(iter(ds))
print('x:\n', batch_x.numpy())
print('y:\n', batch_y.numpy())

x:
 [[0.16513085 0.9014813  0.6309742 ]
 [0.4345461  0.29193902 0.64250207]
 [0.9757855  0.43509948 0.6601019 ]]
y:
 [0 1 2]


In [13]:
#Repeat
ds = ds_joint.batch(3).repeat(count = 2)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (1, 3) [3]
2 (3, 3) [0 1 2]
3 (1, 3) [3]


In [14]:
ds = ds_joint.repeat(count = 2).batch(3)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (3, 3) [3 0 1]
2 (2, 3) [2 3]


In [20]:
tf.random.set_seed(1)
ds = ds_joint.shuffle(4).batch(2).repeat(3)
for i, (batch_x, batch_y) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (2, 3) [2 1]
1 (2, 3) [0 3]
2 (2, 3) [0 3]
3 (2, 3) [1 2]
4 (2, 3) [3 0]
5 (2, 3) [1 2]
