In [2]:
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

print('Using tensorflow version:', tf.__version__)
print('Device avaliable:', tf.config.list_physical_devices())

Using tensorflow version: 2.3.1
Device avaliable: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU')]


# Constant

In [3]:
tf.constant([[1, 2, 3]])

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [4]:
tf.convert_to_tensor([[1, 2, 3]])

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [5]:
tf.convert_to_tensor([[1, 2, 3]]).numpy()

array([[1, 2, 3]], dtype=int32)

In [6]:
tf.convert_to_tensor([[1, 2, 3]], dtype = tf.float32)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [7]:
tf.Variable([[1, 2, 5]])

<tf.Variable 'Variable:0' shape=(1, 3) dtype=int32, numpy=array([[1, 2, 5]], dtype=int32)>

In [8]:
v = tf.Variable(2)

In [9]:
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>


In [10]:
v.assign(1)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>


In [12]:
c = tf.convert_to_tensor(np.random.randn(2, 3))
v = tf.Variable(np.random.randn(3, 1))
print('Multiplication', tf.matmul(c, v))

Multiplication tf.Tensor(
[[ 6.2859367 ]
 [-1.43676309]], shape=(2, 1), dtype=float64)


#Automatic Differentiation

In [14]:
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**3
    dy_dx = tape.gradient(y, x)
    print('gradient at x={} is {}'.format(x.numpy(), dy_dx.numpy()))

gradient at x=3.0 is 27.0


In [15]:
x = tf.Variable(3.0)
with tf.GradientTape() as t1:
    with tf.GradientTape() as t2:
        y = x**3
        dy_dx = t2.gradient(y, x)
        d2y_dx2 = t1.gradient(dy_dx, x)
        print('2nd order at gradient at x = {} is {} '.format(x.numpy(), d2y_dx2.numpy()))

2nd order at gradient at x = 3.0 is 18.0 


# Watching Tensors

In [18]:
x = tf.constant(3.0)
with tf.GradientTape() as tape:
    y = x**3
    dy_dx = tape.gradient(y, x)
    print('gradient at x={} is {}'.format(x.numpy(), dy_dx))

gradient at x=3.0 is None


In [ ]:
x = tf.constant(3.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = x**3
    
    dy_dx = tape.gradient(y, x)
    print('gradient at x={} is {}'.format(x.numpy(), dy_dx))

#Persistant Tape

In [20]:
x = tf.Variable(3.0)
with tf.GradientTape(persistent = True) as tape:
    y = x**3
    z = 2*y
    
    dz_dy = tape.gradient(z, y)
    dy_dx = tape.gradient(y, x)
    dz_dx = tape.gradient(z, x)
    
    del tape
    
    print('dz_dy:', dz_dy.numpy())
    print('dy_dx:', dy_dx.numpy())
    print('dz_dx:', dz_dx.numpy())

dz_dy: 2.0
dy_dx: 27.0
dz_dx: 54.0
